---
# gitops/apps/catalog/kustomization.yaml
# Kustomize entry point para el Dark Service catalog.bc.internal
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
