# flux/clusters/bc-workload/messaging/nats-provisioning-gw/kustomization.yaml
# El IngressRouteTCP ha sido movido a networking/routes/ porque requiere CRDs de Traefik.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
